import { HackathonEventTemplate } from './types';

export const workshopTemplates: HackathonEventTemplate[] = [
  {
    name: "Design Sprint 5 días",
    phases: [
      // DÍA 1
      { id: crypto.randomUUID(), name: 'DÍA 1: Bienvenida y contexto', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Establecer meta a largo plazo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Mapeo del problema', duration: 75 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Preguntas sprint', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Entrevistas con expertos', duration: 90 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Definir el objetivo', duration: 75 },
      { id: crypto.randomUUID(), name: 'DÍA 1: Tarea para casa', duration: 30 },
      // DÍA 2
      { id: crypto.randomUUID(), name: 'DÍA 2: Compartir inspiraciones', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Demos relámpago', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Dividir o agrupar', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Tomar notas', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Crazy 8\'s', duration: 105 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Solution Sketch', duration: 150 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 2: Preparación para mañana', duration: 45 },
      // DÍA 3
      { id: crypto.randomUUID(), name: 'DÍA 3: Museo de arte', duration: 90 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Crítica rápida', duration: 75 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Votación estructurada', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Decidir el ganador', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Batalla o fusión', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Break y preparación', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Crear storyboard', duration: 120 },
      { id: crypto.randomUUID(), name: 'DÍA 3: Planear prototipo', duration: 30 },
      // DÍA 4
      { id: crypto.randomUUID(), name: 'DÍA 4: Dividir y conquistar', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 4: Prototipar sesión 1', duration: 180 },
      { id: crypto.randomUUID(), name: 'DÍA 4: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 4: Prototipar sesión 2', duration: 150 },
      { id: crypto.randomUUID(), name: 'DÍA 4: Ensayo', duration: 45 },
      { id: crypto.randomUUID(), name: 'DÍA 4: Ajustes finales', duration: 45 },
      // DÍA 5
      { id: crypto.randomUUID(), name: 'DÍA 5: Preparación', duration: 30 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Entrevista 1', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Debrief rápido', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Entrevista 2', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Debrief rápido', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Entrevista 3', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Debrief rápido', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Entrevista 4', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Entrevista 5', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Síntesis final', duration: 60 },
      { id: crypto.randomUUID(), name: 'DÍA 5: Próximos pasos', duration: 30 },
    ],
  },
  {
    name: "Design Sprint (4 días)",
    phases: [
        // DÍA 1
        { id: crypto.randomUUID(), name: 'DÍA 1: Bienvenida y contexto', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Establecer meta a largo plazo', duration: 45 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Mapeo del problema', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Preguntas sprint', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Definir el objetivo', duration: 45 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Almuerzo', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Entrevistas con expertos', duration: 90 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Compartir inspiraciones', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Tomar notas (How Might We)', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Crazy 8\'s', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 1: Solution Sketch', duration: 60 },
        // DÍA 2
        { id: crypto.randomUUID(), name: 'DÍA 2: Museo de arte', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Crítica rápida', duration: 90 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Votación estructurada', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Almuerzo', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Decidir el ganador', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Batalla o fusión', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Crear storyboard', duration: 120 },
        { id: crypto.randomUUID(), name: 'DÍA 2: Planear prototipo', duration: 30 },
        // DÍA 3
        { id: crypto.randomUUID(), name: 'DÍA 3: Dividir y conquistar', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Prototipar sesión 1', duration: 180 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Almuerzo', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Prototipar sesión 2', duration: 150 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Ensayo', duration: 45 },
        { id: crypto.randomUUID(), name: 'DÍA 3: Ajustes finales', duration: 45 },
        // DÍA 4
        { id: crypto.randomUUID(), name: 'DÍA 4: Preparación', duration: 30 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Entrevista 1', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Debrief rápido', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Entrevista 2', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Debrief rápido', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Almuerzo', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Entrevista 3', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Debrief rápido', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Entrevista 4', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Entrevista 5', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Síntesis final', duration: 60 },
        { id: crypto.randomUUID(), name: 'DÍA 4: Próximos pasos', duration: 30 },
    ],
  },
  {
    name: "Human-Centered Design (1 día)",
    phases: [
      // FASE 1: INSPIRACIÓN (Hear)
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Bienvenida e introducción a HCD', duration: 20 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Definición del desafío', duration: 30 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Preparación para salir al campo', duration: 20 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Investigación de campo', duration: 90 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Entrevistas con usuarios', duration: 60 },
      { id: crypto.randomUUID(), name: 'INSPIRACIÓN: Almuerzo', duration: 60 },
      // FASE 2: IDEACIÓN (Create)
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Compartir historias', duration: 30 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Identificar patrones y insights', duration: 45 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Definir oportunidades', duration: 30 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Brainstorming', duration: 60 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Selección de ideas', duration: 20 },
      // FASE 3: IMPLEMENTACIÓN (Deliver)
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Prototipado rápido', duration: 90 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Feedback de prototipos', duration: 45 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Iteración', duration: 30 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Plan de acción', duration: 30 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Presentación final', duration: 30 },
      { id: crypto.randomUUID(), name: 'IMPLEMENTACIÓN: Cierre y reflexiones', duration: 20 },
    ],
  },
  {
    name: "Design Thinking (1 día)",
    phases: [
        // FASE 1: EMPATIZAR
        { id: crypto.randomUUID(), name: 'EMPATIZAR: Bienvenida e introducción a Design Thinking', duration: 20 },
        { id: crypto.randomUUID(), name: 'EMPATIZAR: Definición del problema', duration: 25 },
        { id: crypto.randomUUID(), name: 'EMPATIZAR: Mapa de empatía', duration: 40 },
        { id: crypto.randomUUID(), name: 'EMPATIZAR: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'EMPATIZAR: Entrevistas y observación', duration: 60 },
        // FASE 2: DEFINIR
        { id: crypto.randomUUID(), name: 'DEFINIR: Síntesis de hallazgos', duration: 30 },
        { id: crypto.randomUUID(), name: 'DEFINIR: Point of View', duration: 25 },
        { id: crypto.randomUUID(), name: 'DEFINIR: Almuerzo', duration: 60 },
        { id: crypto.randomUUID(), name: 'DEFINIR: How Might We', duration: 30 },
        // FASE 3: IDEAR
        { id: crypto.randomUUID(), name: 'IDEAR: Warm up creativo', duration: 15 },
        { id: crypto.randomUUID(), name: 'IDEAR: Brainstorming', duration: 50 },
        { id: crypto.randomUUID(), name: 'IDEAR: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'IDEAR: Selección de ideas', duration: 30 },
        // FASE 4: PROTOTIPAR
        { id: crypto.randomUUID(), name: 'PROTOTIPAR: Introducción al prototipado', duration: 15 },
        { id: crypto.randomUUID(), name: 'PROTOTIPAR: Construcción de prototipos', duration: 75 },
        { id: crypto.randomUUID(), name: 'PROTOTIPAR: Break', duration: 15 },
        { id: crypto.randomUUID(), name: 'PROTOTIPAR: Refinamiento', duration: 30 },
        // FASE 5: TESTEAR
        { id: crypto.randomUUID(), name: 'TESTEAR: Testing con usuarios', duration: 45 },
        { id: crypto.randomUUID(), name: 'TESTEAR: Feedback y aprendizajes', duration: 30 },
        { id: crypto.randomUUID(), name: 'TESTEAR: Iteración rápida', duration: 30 },
        { id: crypto.randomUUID(), name: 'TESTEAR: Plan de siguiente pasos', duration: 20 },
        { id: crypto.randomUUID(), name: 'TESTEAR: Cierre y reflexiones', duration: 15 },
    ],
  },
  {
    name: "Lean Startup (1 día)",
    phases: [
      // FASE 1: BUILD (Construir)
      { id: crypto.randomUUID(), name: 'BUILD: Bienvenida e introducción a Lean Startup', duration: 20 },
      { id: crypto.randomUUID(), name: 'BUILD: Identificar el problema', duration: 30 },
      { id: crypto.randomUUID(), name: 'BUILD: Definir hipótesis clave', duration: 40 },
      { id: crypto.randomUUID(), name: 'BUILD: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'BUILD: Lean Canvas', duration: 60 },
      { id: crypto.randomUUID(), name: 'BUILD: Definir MVP', duration: 45 },
      { id: crypto.randomUUID(), name: 'BUILD: Almuerzo', duration: 60 },
      // FASE 2: MEASURE (Medir)
      { id: crypto.randomUUID(), name: 'MEASURE: Identificar métricas clave', duration: 30 },
      { id: crypto.randomUUID(), name: 'MEASURE: Definir experimentos', duration: 40 },
      { id: crypto.randomUUID(), name: 'MEASURE: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'MEASURE: Crear prototipo de MVP', duration: 90 },
      // FASE 3: LEARN (Aprender)
      { id: crypto.randomUUID(), name: 'LEARN: Testing con clientes potenciales', duration: 60 },
      { id: crypto.randomUUID(), name: 'LEARN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'LEARN: Análisis de resultados', duration: 40 },
      { id: crypto.randomUUID(), name: 'LEARN: Validar o invalidar hipótesis', duration: 30 },
      { id: crypto.randomUUID(), name: 'LEARN: Pivotar o perseverar', duration: 30 },
      { id: crypto.randomUUID(), name: 'LEARN: Plan de acción', duration: 30 },
      { id: crypto.randomUUID(), name: 'LEARN: Cierre y próximos pasos', duration: 20 },
    ],
  },
  {
    name: "This is Service Design (1 día)",
    phases: [
      // FASE 1: INVESTIGACIÓN Y EMPATÍA
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Bienvenida e introducción a Service Design', duration: 20 },
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Definir el servicio a diseñar', duration: 30 },
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Identificar stakeholders', duration: 25 },
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Investigación con usuarios', duration: 60 },
      { id: crypto.randomUUID(), name: 'INVESTIGACIÓN: Shadowing y observación', duration: 45 },
      // FASE 2: ANÁLISIS Y SÍNTESIS
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Almuerzo', duration: 60 },
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Customer Journey Map', duration: 50 },
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Service Blueprint', duration: 50 },
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Identificar pain points', duration: 30 },
      { id: crypto.randomUUID(), name: 'ANÁLISIS: Definir oportunidades', duration: 25 },
      // FASE 3: IDEACIÓN
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Brainstorming de mejoras', duration: 45 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Diseño de touchpoints', duration: 40 },
      { id: crypto.randomUUID(), name: 'IDEACIÓN: Selección de conceptos', duration: 20 },
      // FASE 4: PROTOTIPADO
      { id: crypto.randomUUID(), name: 'PROTOTIPADO: Service Prototyping', duration: 60 },
      { id: crypto.randomUUID(), name: 'PROTOTIPADO: Storyboard de experiencia', duration: 30 },
      { id: crypto.randomUUID(), name: 'PROTOTIPADO: Break', duration: 15 },
      { id: crypto.randomUUID(), name: 'PROTOTIPADO: Role-playing del servicio', duration: 45 },
      // FASE 5: TESTING
      { id: crypto.randomUUID(), name: 'TESTING: Testing con usuarios', duration: 40 },
      { id: crypto.randomUUID(), name: 'TESTING: Feedback y aprendizajes', duration: 30 },
      { id: crypto.randomUUID(), name: 'TESTING: Iteración del servicio', duration: 25 },
      { id: crypto.randomUUID(), name: 'TESTING: Plan de implementación', duration: 20 },
      { id: crypto.randomUUID(), name: 'TESTING: Cierre y próximos pasos', duration: 15 },
    ],
  },
];